spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.xnonrfatbmqudqynvprt
spring.datasource.password=F1n@rfin_126812
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.query.startup_check=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://xnonrfatbmqudqynvprt.supabase.co/auth/v1