spring.application.name=backend
server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.xnonrfatbmqudqynvprt
spring.datasource.password=F1n@rfin_126812
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.query.startup_check=false

# Necesario junto con prepareThreshold=0 para que Hibernate no intente
# cachear/reusar prepared statements contra el pooler de Supabase (PgBouncer modo transaction)
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

# CORRECCIÓN: URL del Issuer de Supabase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://xnonrfatbmqudqynvprt.supabase.co/auth/v1