spring.application.name=backend
server.port=8080

# Base de datos
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.xnonrfatbmqudqynvprt
spring.datasource.password=F1n@rfin_126812
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.query.startup_check=false

# CORRECCIÓN: URL del Issuer de Supabase
# La ruta correcta para que Spring detecte las llaves es la raíz del Auth de tu proyecto
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://xnonrfatbmqudqynvprt.supabase.co/auth/v1